### ISSUE TITLE
Localization语言模板问题 shiro 注解 RequiresPermissions

### ISSUE THREAD

**Issue by TomYule** [nutzam/nutzmore#132]
`@Localization(value = "locales/", defaultLocalizationKey = "zh-CN")`
国际话语言设置
user.require.auth=对不起您没有权限操作

`@RequiresPermissions("app:serviceFeeItem:edit")`
返回的json
没有被处理这个是什么原因呢

`{"ok":false,"msg":"user.require.auth","type":"user.require.auth"}`

**Comment by wendal** [comment]
这个嘛...

**Comment by TomYule** [comment]
如何改 兽总  可以 给点指点 我看看  我能不能解决

**Comment by wendal** [comment]
改NutShiroProcessor嘛, 从Mvcs.getMessage取
