### ISSUE TITLE
建议：在ShiroProcess中添加跳回的支持。

### ISSUE THREAD

**Issue by whitemay** [nutzam/nutzmore#18]
建议在NutShiroProcessor的第126行与127行之间加一句话：

`WebUtils.saveRequest(ac.getRequest());`

从而与Shiro本身的登录后跳回机制相衔接。
另外，该类中的loginUri和noAuthUri该怎么用？只是为了继承后覆盖吗？

**Comment by Rekoe** [comment]
@whitemay  添加了
