### ISSUE TITLE
json4excel如何自定义控制字段应该是行还是列？

### ISSUE THREAD

**Issue by projack1** [nutzam/nutzmore#34]
1、如何通过注解控制字段的行和列？
2、如何通过注解实现表格的一行多列的情况？

**Comment by pangwu86** [comment]
1.  行是根据你传入的数据集合的数量来定的 列是pojo对象的声明顺序，或者可以根据J4EConf来配置
2. 一行多列？没懂啥意思

**Comment by pangwu86** [comment]
没后续了，关了
