### ISSUE TITLE
nutz-integration-jcache底层使用nutz-plugins-cache来实现

### ISSUE THREAD

**Issue by Wizzercn** [nutzam/nutzmore#40]
1、支持配多个缓存名（redis对应的是命名空间）；
2、支持按缓存名（redis对应的是命名空间）清空缓存；
3、支持缓存名及时效时间的配置（不设置失效时间就是永久缓存，需手动更新）；
4、支持ehcache或redis切换配置；
6、支持通配符删除缓存；demo代码：
`    @Override
    public void evict(Object key) {
        final String keyf = this.getName()+":"+(String) key;
        if (keyf.endsWith("*")) {
            Set<String> set = jedis().keys(keyf);
            for (String it : set) {
                jedis().del(it.getBytes());
            }
        } else
            jedis().del(keyf.getBytes());
    }

    /**
     * 清空当前命名空间
     */
    @Override
    public void clear() {
        this.evict("*");
        //jedis().flushDB();
    }`

**Comment by wendal** [comment]
不靠谱, 除非你自己实现了

**Comment by Wizzercn** [comment]
我提的需求基本都是项目中比较实际的需求，比如以前提的好几个issue，隔了两年nutz才提供支持，还有那个插件化也提了很久的，希望这个需求也能得到重视。。。

**Comment by wendal** [comment]
待我写完zookeeper再说
