### ISSUE TITLE
是否有必要实现个地图轨迹相关的插件

### ISSUE THREAD

**Issue by howe** [nutzam/nutzmore#42]
类似计算 2个经纬度的间距
给定经纬度与半径范围查出数据库内对应经纬度的值
各种地图坐标系纠偏与互相坐标系的转换
经纬度转定位地址
等等等。。。
应用场景 (伪)自动驾驶 物联网 车联网 o2o 物流 监控等业务 @wendal

**Comment by ninggf** [comment]
很有必要

**Comment by ywjno** [comment]
GEO自己算啊

**Comment by howe** [comment]
各种地图坐标系纠偏与互相坐标系的转换 wgs84 <--> bd09 <--> ggcj02
网上实现方式 是类似算法计算偏差 其实不准
比较准确的方式是查库法 长期数据学习

经纬度转定位地址 (lon,lat) <--->localtion
等等等。。。

算距离之类的直接用mysql5.7或者redis3.2的自带geo算法吧
