### ISSUE TITLE
nutz-plugins-hotplug是否可以降级到支持1.7?

### ISSUE THREAD

**Issue by qinerg** [nutzam/nutzmore#43]
nutz-plugins-hotplug里好像仅有排序依赖1.8的特性，是否可以修改以支持更低的jdk?

**Comment by wendal** [comment]
改呗

**Comment by wendal** [comment]
没看出来哪里用jdk8特性了? 提示一下?

**Comment by qinerg** [comment]
切换到1.7下 Hotplug 类的第324行   hclist.sort(new Comparator<HotplugConfig>()  报错，切回1.8即可正常编译。

**Comment by wendal** [comment]
原来是hclist.sort类是JDK8才有的方法
