### ISSUE TITLE
autoloadcache的ShardedCachePointCut构造方法有变动，老的redis-pool.js需要更新

### ISSUE THREAD

**Issue by crskyp** [nutzam/nutzmore#44]
autoloadcache的ShardedCachePointCut构造方法有变动，老的redis-pool.js需要更新

**Comment by crskyp** [comment]
test代码有更新：https://github.com/qiujiayu/AutoLoadCache-nutz/blob/master/src/test/resources/ioc/redis-pool.js

**Comment by wendal** [comment]
fixed
