### ISSUE TITLE
关于\00026的问题

### ISSUE THREAD

**Issue by LovelyIsJustice** [nutzam/nutzmore#58]
在QRCodeFormat中设置setEncode
如果值为“UTF-8”,我使用扫描枪扫描二维码会在字符串前无故加入“\00026”这个字段
如果改为"utf-8"，就是改为小写就不会出现这样的情况
---------------------------------------
刚刚写错了 写到nutzam里面去了，这里重新发一下

**Comment by ywjno** [comment]
b62b19e

**Comment by ywjno** [comment]
能不能帮忙试试用 encode 设置成 `GBK` 的话能否被扫码枪识别
