### ISSUE TITLE
主键写入数据库的问题

### ISSUE THREAD

**Issue by zicai1026** [nutzam/nutzmore#59]
数据库信息：
- Mysql : character_set_client=utf8
- Mysql : character_set_connection=utf8
- Mysql : character_set_database=utf8
- Mysql : character_set_filesystem=binary
- Mysql : character_set_results=
- Mysql : character_set_server=utf8
- Mysql : character_set_system=utf8
- Mysql : character_sets_dir=/usr/share/mysql/charsets/
- Mysql : binlog_format=STATEMENT
- Mysql : database=nutz_demo

主键设置：
`@Name`
` private String id = R.UU32();`
结果：写入数据正常

主键设置：
`@Name`
`@Prev(els = @EL("uuid()"))`
` private String id;`
结果：写入数据错误
`!Nutz SQL Error: 'INSERT INTO t_role(id,name,create_time) VALUES('c9d6ad67144a41518f68da4236ae63f0','(b43edb4959cc45dcbd4a6ed26ebcec94)','2017-07-18 17:03:09') ' PreparedStatement: 'INSERT INTO t_role(id,name,create_time) VALUES(?,?,?) ' CaseMessage=Cannot execute statement: impossible to write to binary log since BINLOG_FORMAT = STATEMENT and at least one table uses a storage engine limited to row-based logging. InnoDB is limited to row-logging when transaction isolation level is READ COMMITTED or READ UNCOMMITTED.`

**Comment by wendal** [comment]
https://nutz.cn/yvr/t/vmh7m1i450hg5q9fps87ink4jd

**Comment by zicai1026** [comment]
使用的是 nutz-plugins-spring-boot-starter， 请问该怎么解决呢？

**Comment by wendal** [comment]
改my.ini/my.cnf里面的binlog-format配置

**Comment by zicai1026** [comment]
谢谢大佬，可以了
