### ISSUE TITLE
json4excel 插件处理多个sheet的问题

### ISSUE THREAD

**Issue by Rekoe** [nutzam/nutzmore#61]
好像处理完一个流就关闭了 再用其它的还需要再加载一次，
@pangwu86 提供一个回调属性的方法？

**Comment by pangwu86** [comment]
现在是默认只处理了一步工作，所以关闭了流，你的需求是要基于Workbook进行多步操作，这个准备在J4E2中实现，还在开发中

**Comment by pangwu86** [comment]
或者你可以先改下源码，把最后一步saveExcel替换成你要返回Workbook，然后手动调用saveExcel

**Comment by pangwu86** [comment]
这个已经解决了，开放直接操作sheet的接口了
