### ISSUE TITLE
当使用RedisService时会打印过多的无效日志

### ISSUE THREAD

**Issue by 251505453** [nutzam/nutzmore#64]
打印内容如下：
impl.NutIoc (NutIoc.java:151) - Get 'redis'<interface org.nutz.aop.MethodInterceptor>
impl.NutIoc (NutIoc.java:151) - Get 'redis'<interface org.nutz.aop.MethodInterceptor>
impl.NutIoc (NutIoc.java:151) - Get 'redis'<interface org.nutz.aop.MethodInterceptor>
impl.NutIoc (NutIoc.java:151) - Get 'redis'<interface org.nutz.aop.MethodInterceptor>
impl.NutIoc (NutIoc.java:151) - Get 'redis'<interface org.nutz.aop.MethodInterceptor>
。。。

**Comment by wendal** [comment]
不是无效日志, 是因为RedisService每个方法都标注了@Aop,需要取redis拦截器

看来要优化一下, 美观一点点
