### ISSUE TITLE
Nutz-plugins-Undertow不兼容Undertow2.00Alpha1版本

### ISSUE THREAD

**Issue by albinhdk** [nutzam/nutzmore#67]
基本现象是：
使用了Undertow2.0.0Alpha1的时候，在Linux的Web环境下，页面的静态资源加载（特别是JS），会出现
：加载困难，JS内容混淆等问题。
具体原因不太明确，不过换成1.4.20Final版本，就没这个问题、

请作者辛苦一下，查一下吧

**Comment by ywjno** [comment]
2.0.0Alpha1比1.4.20Final还要老，你确定要用alpha版的？

**Comment by wendal** [comment]
查了一下, 貌似2.0已经不开发了...

2.0.0Alpha2都已经是一年前的事

**Comment by albinhdk** [comment]
这命名规则我也是醉了！

**Comment by qinerg** [comment]
Undertow 活跃维护的版本线还是 1.4.x 系列， undertow-io/undertow 上 1.4.20 是最新的版本。
如果有新的版本会一直跟进下去的。
