### ISSUE TITLE
来个disque插件？

### ISSUE THREAD

**Issue by howe** [nutzam/nutzmore#69]
项目地址：
https://github.com/antirez/disque

Disque 是一个内存储存的分布式任务队列实现， 它由 Redis 的作者 Salvatore Sanfilippo (@antirez)开发， 目前正处于Disque 1.0.rc.1 阶段。

**Comment by wendal** [comment]
https://github.com/xetorthio/jedisque

**Comment by wendal** [comment]
这项目停更1年多了,你还打算用??

**Comment by howe** [comment]
这么屌坑 我还以为是更新的慢啊

**Comment by ywjno** [comment]
老实用 mq 吧

**Comment by howe** [comment]
关了关了
