### ISSUE TITLE
nutz中自定义sql需要一个类似include的功能

### ISSUE THREAD

**Issue by qianchengjun** [nutzam/nutzmore#70]
select distinct a.* from tdocument a
left join tdocumentlabelmap b on a.id = b.documentId
left join tcommonloginuser c on a.createuserid = c.id
	<%layout("getEmployeeReadListWhere.sql",{
		companyId : companyId,
		loginUserId : loginUserId,
		employeeId : employeeId,
		documentTypeId : documentTypeId,
		labelId : labelId
	}){
	%>
	order by a.status asc,a.toplevel desc,a.toptime desc,a.createTime desc
	<%}%>

[DEBUG] 11:23:29.265 org.nutz.dao.impl.sql.run.NutDaoExecutor.printSQL(NutDaoExecutor.java:388) - select distinct a.* from tdocument a
left join tdocumentlabelmap b on a.id = b.documentId
left join tcommonloginuser c on a.createuserid = c.id
getEmployeeReadListWhere.sql LIMIT 0, 10

**Comment by wendal** [comment]
搞定, layout的文件名必须是/开头的哦,为classpath下的路径
