### ISSUE TITLE
来搞个NutzBoot吗?

### ISSUE THREAD

**Issue by wendal** [nutzam/nutzmore#72]
先挖坑

**Comment by zozoh** [comment]
列个功能表？

**Comment by howe** [comment]
搞起来 看隔壁 jfianl都有 jboot哈哈

**Comment by ninggf** [comment]
__搞起__ **坑要大一点**

**Comment by Wizzercn** [comment]
占座

**Comment by ywjno** [comment]
建议另开个项目弄这个，

**Comment by wendal** [comment]
叫啥名字好呢? nutzboot? nboot? 反正都是简称 NB ~_~

**Comment by ywjno** [comment]
nutzboot 吧

**Comment by wendal** [comment]
https://github.com/nutzam/nutzboot

**Comment by chejingchi** [comment]
有了nutzboot是不是还要搞个nutzcloud啊

**Comment by wendal** [comment]
这次用码云做主库吧

https://gitee.com/nutz/nutzboot
https://gitee.com/nutz/nutzcloud

**Comment by elkan1788** [comment]
好是期待呀，nutz micro service come inning.

**Comment by qinerg** [comment]
简化开发，一键启动，组件可任意替换...
直接 java8 起，高起点，很NB

**Comment by wendal** [comment]
Java8是必须的, ^_6
Jetty 9.3
tomcat 8.5
undertow 1.4.x

**Comment by elkan1788** [comment]
考虑下`Service Mesh`--> [istio](http://istio.doczh.cn/)
