### ISSUE TITLE
增加nutz-plugins-dict字典插件

### ISSUE THREAD

**Issue by denghuafeng** [nutzam/nutzmore#81]
后台开发中经常牵涉到一些类型字典，例如（用户表的类型字段，分普通会员、高级会员等），如果用常规的常量标识不可取，没法统一，也没法很好的标识意义，推荐用枚举。
      而前段展示类型字段值的字面意思时，通常是生拉硬写，各种if判断来展示不同的字面意思，不好维护，改动一处，要改动多处。 
      而此插件的开发目的是解决这些问题，让通过后台枚举配置注解的方式，生成可配置格式的前段json字典串，及全局的字典map，供前段调用等。

**Comment by happyday517** [comment]
个人理解这个需求和你所做的项目高度相关，应该你自己开发，自己用
不应该放到nutzmore里

**Comment by denghuafeng** [comment]
通用的 自己已经开发完了 我弄个issue 只是为了准备发布

**Comment by ywjno** [comment]
可以考虑自己发布到maven上啊，不用放到这里面的

**Comment by denghuafeng** [comment]
目前代码有些引用nutz的，暂时先发布到这

**Comment by denghuafeng** [comment]
已经添加

**Comment by denghuafeng** [comment]
用了jdk 1.8 语法了 你已经修复了吧
