### ISSUE TITLE
nutz-integration-json4excel  关于日期格式化及父类字段等问题

### ISSUE THREAD

**Issue by Wizzercn** [nutzam/nutzmore#86]
1. 时间戳字段，如何格式化日期？
`    @Column
    @Comment("报名时间")
    @J4EDefine(type = J4EColumnType.DATE)
    @J4EDateFormat(from = "",to = "yyyy-MM-dd HH:mm:ss")
    @Prev(els = @EL("now()"))
    @ColDefine(type = ColType.INT)
    private Integer createAt;`

2、父类字段没法加 J4EIgnore ，如何在导出时忽略？

3、可否根据值进行输出判断，如 status=1 审核通过、status=2 未通过？

**Comment by wendal** [comment]
强势围观

**Comment by zozoh** [comment]
@pangwu86 要出场了

**Comment by pangwu86** [comment]
楼上的2位。。。

**Comment by pangwu86** [comment]
@Wizzercn 

看下 https://github.com/nutzam/nutzmore/blob/master/nutz-integration-json4excel/src/test/java/org/nutz/integration/json4excel/issue/IssueRun.java 最下面的test_issue86即可

里面模仿你的需求建了类，上面3个问题都有解决方案

**Comment by Wizzercn** [comment]
@pangwu86 父类字段还输出怎么回事呢？

**Comment by Wizzercn** [comment]
额 还需要手动配置啊……

**Comment by pangwu86** [comment]
父类又不能加注解，只能是配置
