### ISSUE TITLE
excel单元格保存的是公式如何解决！！！

### ISSUE THREAD

**Issue by jeasonsilver** [nutzam/nutzmore#92]
当excel单元格保存的是公式（公式可能跨sheet取值来计算：=sheet2的C1+sheet1的A1）时，导入失败（空值）

**Comment by wendal** [comment]
给出代码

**Comment by jeasonsilver** [comment]
给什么代码

**Comment by wendal** [comment]
那你这是问啥? POI的使用问题???

**Comment by jeasonsilver** [comment]
json4Excel导入excel时，如果某单元格存的是公式的时候，json4Excel程序的读取的是空值

**Comment by jeasonsilver** [comment]
@pangwu86
