### ISSUE TITLE
导入excel时，如何将excel某一列的值作为数据库表字段对映，将其他数据导入进去

### ISSUE THREAD

**Issue by jeasonsilver** [nutzam/nutzmore#93]
excel格式：
column1| a1 | 2 | 1 | 1 | 1
column2 | b1 | 2 | 3 | 4 | 6
column3 | c1 | 3 | 4 | 5 | 6
column4 | d1 | 1 | 1 | 1 | 1

导入数据库后的表样式：

column1| column2 | column3 | column4
a1 | b1 | c1 | d1
2 | 2 | 3 | 1
1 | 3 | 4 | 1
1 | 4 | 5 | 1
1 | 6 | 6 | 1

**Comment by wendal** [comment]
这是J4E相关的东西??

**Comment by jeasonsilver** [comment]
j4e的实体映射的excel表字段如果对应的excel是竖向排列着的时候……

**Comment by jeasonsilver** [comment]
@ @pangwu86
